# Generated by Django 6.0 on 2025-12-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('editora', models.CharField(max_length=200, verbose_name='Editora')),
                ('ano_publicacao', models.IntegerField(verbose_name='Ano de Publicação')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('num_paginas', models.IntegerField(verbose_name='Número de Páginas')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('capa_url', models.URLField(blank=True, verbose_name='URL da Capa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
