# Generated by Django 6.0 on 2025-12-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(default='Não categorizado', max_length=100, verbose_name='Categoria/Gênero'),
        ),
    ]
