# Generated by Django 6.0 on 2025-12-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_remove_livro_isbn_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('lendo', 'Lendo Agora'), ('lido', 'Lido'), ('emprestado', 'Emprestado'), ('quero_ler', 'Quero Ler')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
