# Generated by Django 6.0 on 2025-12-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_livro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='emprestado_para',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
